### ISSUE TITLE
Watch wrangler.toml files for changes

### ISSUE THREAD

**Issue by jamesopstad** [flarelabs-net/vite-plugin-cloudflare#11]

**Comment by dario-piotrowicz** [comment]
@jamesopstad what do you think it should happen when a toml file changes?

Should we restart the worker associated to that toml file? or restart everything? (potentially with a full page reload)

I think that restarting everything makes sense since:
 - the changes in a worker's toml file can effect other workers that bound to it
 - developers rarely change the toml file so fully realoding everything, which also doesn't take that long, doesn't seem a problem in this case

what do you think?

**Comment by jamesopstad** [comment]
I don't think it's possible to only restart a single worker when they are running in the same Miniflare instance (correct me if I'm wrong). So I think we need to wrap up all the logic to create the Miniflare options and then call `Miniflare.setOptions` when any of the `wrangler.toml` files change. We'll also need to rerun this:

https://github.com/flarelabs-net/vite-plugin-cloudflare/blob/dad67001939853d1ee0ac5bdb8d107f4950c81bb/packages/vite-plugin-cloudflare/src/index.ts#L201-L211

It's straightforward but involves moving a lot of code around so might be easier to do when the other PRs are merged.

**Comment by dario-piotrowicz** [comment]
Yeah Miniflare can't restart a single worker... I mentioned that as I was thinking that we do can restart a single worker on our end by restarting it's runner, clearing its module graph, etc...

But yeah you're right, it doesn't make much sense actually, miniflare has a single `setOptions` and that restarts everything, and we do need to run it to get the updated bindings... so indeed I don't think we really have much of a choice actually 😕 :+1:
